package exo2;/*
 * Automatically generated by jrpcgen 1.0.5 on 3/18/20, 2:45 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * A collection of constants used by the "Calcul" ONC/RPC program.
 */
public interface Calcul {
    public static final int add_1 = 1;
    public static final int mod_1 = 5;
    public static final int CALCUL_VERSION_FLOAT = 2;
    public static final int mul_2 = 3;
    public static final int mul_1 = 3;
    public static final int div_2 = 4;
    public static final int div_1 = 4;
    public static final int calcul_null_2 = 0;
    public static final int calcul_null_1 = 0;
    public static final int CALCUL_PROG = 0x22222220;
    public static final int sub_2 = 2;
    public static final int sub_1 = 2;
    public static final int CALCUL_VERSION_INT = 1;
    public static final int add_2 = 1;
}
// End of Calcul.java
