package exo1;/*
 * Automatically generated by jrpcgen 1.0.5 on 3/18/20, 2:36 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

import java.net.InetAddress;

import org.acplt.oncrpc.server.*;

/**
 */
public abstract class HelloWorldServerStub extends OncRpcServerStub implements OncRpcDispatchable {

    public HelloWorldServerStub()
           throws OncRpcException, IOException {
        this(0);
    }

    public HelloWorldServerStub(int port)
           throws OncRpcException, IOException {
        this(null, port);
    }

    public HelloWorldServerStub(InetAddress bindAddr, int port)
           throws OncRpcException, IOException {
        info = new OncRpcServerTransportRegistrationInfo [] {
            new OncRpcServerTransportRegistrationInfo(HelloWorld.HELLO_WORLD_PROG, 1),
        };
        transports = new OncRpcServerTransport [] {
            new OncRpcUdpServerTransport(this, bindAddr, port, info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, info, 32768)
        };
    }

    public void dispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
           throws OncRpcException, IOException {
        if ( version == 1 ) {
            switch ( procedure ) {
            case 0: {
                call.retrieveCall(XdrVoid.XDR_VOID);
                hello_world_null_1();
                call.reply(XdrVoid.XDR_VOID);
                break;
            }
            case 1: {
                Chaine args$ = new Chaine();
                call.retrieveCall(args$);
                Chaine result$ = hello_world_1(args$);
                call.reply(result$);
                break;
            }
            default:
                call.failProcedureUnavailable();
            }
        } else {
            call.failProcedureUnavailable();
        }
    }

    public abstract void hello_world_null_1();

    public abstract Chaine hello_world_1(Chaine arg1);

}
// End of HelloWorldServerStub.java
