package exo1;/*
 * Automatically generated by jrpcgen 1.0.5 on 3/18/20, 2:36 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * A collection of constants used by the "HelloWorld" ONC/RPC program.
 */
public interface HelloWorld {
    public static final int HELLO_WORLD_VERSION_1 = 1;
    public static final int HELLO_WORLD_PROG = 0x22222220;
    public static final int hello_world_1 = 1;
    public static final int hello_world_null_1 = 0;
}
// End of HelloWorld.java
