/*
 * Automatically generated by jrpcgen 1.0.5 on 3/18/20, 3:31 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;
import java.util.Objects;

public class Chaine implements XdrAble {

    public String value;

    public Chaine() {
    }

    public Chaine(String value) {
        this.value = value;
    }

    public Chaine(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeString(value);
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        value = xdr.xdrDecodeString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Chaine chaine = (Chaine) o;
        return Objects.equals(value, chaine.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }
}
// End of Chaine.java
