/*
 * Automatically generated by jrpcgen 1.0.5 on 3/18/20, 3:31 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;

/**
 * A collection of constants used by the "Chat" ONC/RPC program.
 */
public interface Chat {
    public static final int resyncMessages_1 = 2;
    public static final int CHAT_PROG = 0x22222220;
    public static final int CHAT_VERSION = 1;
    public static final int connect_1 = 0;
    public static final int sendMessage_1 = 1;
}
// End of Chat.java
