/*
 * Automatically generated by jrpcgen 1.0.5 on 3/18/20, 3:31 PM
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://acplt.org/ks/remotetea.html for details
 */
import org.acplt.oncrpc.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

public class MessageList implements XdrAble {

    public Chaine [] value;
    public ArrayList<Chaine> values;

    public MessageList() {
        values = new ArrayList<>();
    }

    public MessageList(Chaine [] value) {
        values = new ArrayList<>(Arrays.asList(value));
    }

    public MessageList(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        { int $size = values.size(); xdr.xdrEncodeInt($size); for ( int $idx = 0; $idx < $size; ++$idx ) { values.get($idx).xdrEncode(xdr); } }
    }

    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        {
            int $size = xdr.xdrDecodeInt(); value = new Chaine[$size]; for ( int $idx = 0; $idx < $size; ++$idx ) { value[$idx] = new Chaine(xdr); }
            values = new ArrayList<>(Arrays.asList(value));
        }
    }

}
// End of MessageList.java
